### ISSUE TITLE
Error message when opening on windows

### ISSUE THREAD

**Issue by Blendify** [tobkum/BlenderUpdater#6]
Windows 10 -64 bit

The program fails to run on windows. See below for error message:
![snip](https://cloud.githubusercontent.com/assets/15183467/14588530/95605282-0499-11e6-916e-1b483031582c.png)

**Comment by tobkum** [comment]
Right, this is due to an installer packaging fault by me. Will upload a new one in a few minutes, could you test this?

**Comment by Blendify** [comment]
yes

**Comment by tobkum** [comment]
Updated the zip, see here: https://github.com/tobkum/BlenderUpdater/releases/tag/0.5

Just let me know if this works. Thanks!

**Comment by Blendify** [comment]
Seems to work fine now. Thanks

**Comment by tobkum** [comment]
Cheers! Thanks for the feedback!
