### ISSUE TITLE
cx_Freeze: Python error in main script

### ISSUE THREAD

**Issue by saltorio** [tobkum/BlenderUpdater#9]
When I try to run BlenderUpdater v1.0 on my work PC (Windows 7 Pro SP 1), I get the error below:

[Screenshot](http://imgur.com/gallery/UOVMV)

**Comment by tobkum** [comment]
Do you get that error immediately after starting the application?

**Comment by saltorio** [comment]
Yes. As soon as I launch the program.

**Comment by tobkum** [comment]
What directory are you starting the application from? Can you test running it straight from a root directory like C:\ (not from the Desktop or any other system folder)?

**Comment by saltorio** [comment]
Tried running it off C:\ without even a parent folder. The error report changed slightly:

[Screenshot](http://imgur.com/gallery/Wr54Y)

**Comment by tobkum** [comment]
That is weird, never happened before. Just to clear it up - you are using the downloaded binary, right?

**Comment by saltorio** [comment]
Yup. Downloading **BlenderUpdater-1.0.win-amd64.zip** from [here](https://github.com/tobkum/BlenderUpdater/releases/).

**Comment by tobkum** [comment]
Can you please try again with the v1.1 and report back?

**Comment by saltorio** [comment]
v1.1 seems to have rectified this issue. Thanks!

**Comment by tobkum** [comment]
Thanks for the feedback!
